### ISSUE TITLE
This repo is dead send me your PRs

### ISSUE THREAD

**Issue by hhirsch** [LarryMad/recipes#1252]
I pronounce this repo dead but I offer to accept all reasonable pull requests here:
https://github.com/hhirsch/recipes

**Comment by aersh** [comment]
This repo was created for educational purpose. It is referenced in a Udacity course on Git and GitHub. Students learn how to fork, submit pull requests, etc using this repo.

**Comment by chizzlebiz** [comment]
I would like to pull but I have been out of the game for quite some time, if anyone else is learning git and wants some 'practice' with a fellow user, then hit me up :+1:

**Comment by Swizz** [comment]
@aersh I got used to teach git by ask them to write dramas, but recipes looks pretty cool.

**Comment by aersh** [comment]
@Swizz I like your idea. Writing dramas is more creative. :)

**Comment by O1984narongsak** [comment]
lol

**Comment by PhysX9900** [comment]
Okay. I just saw this. This was indeed an educational post. However, what surprises me most is that somebody actually commented on this. Putting all this aside, I do, and inspire to cook good food.
